name: agrote
description: "Agricultural Note"
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add flutter_local_notifications for notifications
  flutter_local_notifications: ^18.0.1

  # Other dependencies
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Example for assets (optional, update if needed)
  # assets:
  #   - images/logo.png

# Additional comments for other developers
# Ensure to run `flutter pub get` to fetch new dependencies.
# For notification support, configure your AndroidManifest.xml as described.
